-- =====================================================================
--  MediQR - Database Script (Oracle SQL / PL-SQL)
--  Tables : PATIENTS, DOCTORS, MEDICAL_RECORDS, MEDICAL_REPORTS,
--           PRESCRIPTIONS, PRESCRIPTION_MEDICINES, QR_CODES
--  Note   : Uses IDENTITY columns, so Oracle 12c or higher is required.
-- =====================================================================


-- =====================================================================
--  0. CLEAN UP (OPTIONAL)
--  Uncomment ONLY when you want to delete old tables and create them again.
--  Delete child tables before parent tables because of foreign keys.
-- =====================================================================
-- DROP TABLE prescription_medicines CASCADE CONSTRAINTS;
-- DROP TABLE prescriptions          CASCADE CONSTRAINTS;
-- DROP TABLE medical_reports        CASCADE CONSTRAINTS;
-- DROP TABLE qr_codes               CASCADE CONSTRAINTS;
-- DROP TABLE medical_records        CASCADE CONSTRAINTS;
-- DROP TABLE doctors                CASCADE CONSTRAINTS;
-- DROP TABLE patients               CASCADE CONSTRAINTS;


-- =====================================================================
--  1. PATIENTS
--  Filled from: register.html, profile.html, doctor "Add Patient" form
--  - email is UNIQUE but nullable (doctor can add patient without email)
--  - password_hash is nullable (doctor-added patients have no login yet)
-- =====================================================================
CREATE TABLE patients (
    patient_id                  NUMBER GENERATED BY DEFAULT AS IDENTITY,
    patient_code                VARCHAR2(30)   NOT NULL,
    patient_name                VARCHAR2(150)  NOT NULL,
    date_of_birth               DATE,
    gender                      VARCHAR2(20),
    blood_group                 VARCHAR2(10),
    phone                       VARCHAR2(20)   NOT NULL,
    email                       VARCHAR2(255),
    password_hash               VARCHAR2(255),
    height                      NUMBER(5,2),
    weight                      NUMBER(5,2),
    allergy                     VARCHAR2(1000),
    existing_disease            VARCHAR2(1000),
    emergency_contact_name      VARCHAR2(150),
    emergency_contact_relation  VARCHAR2(50),
    emergency_contact_phone     VARCHAR2(20),
    address                     VARCHAR2(500),
    city                        VARCHAR2(100),
    state                       VARCHAR2(100),
    profile_photo               VARCHAR2(500),
    status                      VARCHAR2(20)   DEFAULT 'Active' NOT NULL,
    created_at                  TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT pk_patients        PRIMARY KEY (patient_id),
    CONSTRAINT uq_patients_code   UNIQUE (patient_code),
    CONSTRAINT uq_patients_email  UNIQUE (email),
    CONSTRAINT ck_patients_gender CHECK (gender IN ('Male', 'Female', 'Other')),
    CONSTRAINT ck_patients_blood  CHECK (blood_group IN ('A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-')),
    CONSTRAINT ck_patients_status CHECK (status IN ('Active', 'Inactive'))
);


-- =====================================================================
--  2. DOCTORS
--  Filled from: doctor-register.html, doctor-dashboard.html (Settings)
--  - hospital_name is optional
-- =====================================================================
CREATE TABLE doctors (
    doctor_id        NUMBER GENERATED BY DEFAULT AS IDENTITY,
    doctor_name      VARCHAR2(150)  NOT NULL,
    license_number   VARCHAR2(50)   NOT NULL,
    specialization   VARCHAR2(100)  NOT NULL,
    qualification    VARCHAR2(150)  NOT NULL,
    email            VARCHAR2(255)  NOT NULL,
    mobile           VARCHAR2(20)   NOT NULL,
    password_hash    VARCHAR2(255)  NOT NULL,
    hospital_name    VARCHAR2(200),

    CONSTRAINT pk_doctors          PRIMARY KEY (doctor_id),
    CONSTRAINT uq_doctors_license  UNIQUE (license_number),
    CONSTRAINT uq_doctors_email    UNIQUE (email)
);


-- =====================================================================
--  3. MEDICAL_RECORDS
--  Each medical record belongs to one patient and one doctor.
-- =====================================================================
CREATE TABLE medical_records (
    record_id     NUMBER GENERATED BY DEFAULT AS IDENTITY,
    patient_id    NUMBER          NOT NULL,
    doctor_id     NUMBER          NOT NULL,
    record_date   DATE            NOT NULL,
    diagnosis     VARCHAR2(1000),
    treatment     VARCHAR2(1000),

    CONSTRAINT pk_medical_records PRIMARY KEY (record_id),

    CONSTRAINT fk_records_patient
        FOREIGN KEY (patient_id)
        REFERENCES patients (patient_id)
        ON DELETE CASCADE,

    CONSTRAINT fk_records_doctor
        FOREIGN KEY (doctor_id)
        REFERENCES doctors (doctor_id)
);


-- =====================================================================
--  4. MEDICAL_REPORTS
--  record_id is optional because a report can be uploaded without a visit.
-- =====================================================================
CREATE TABLE medical_reports (
    report_id     NUMBER GENERATED BY DEFAULT AS IDENTITY,
    patient_id    NUMBER          NOT NULL,
    record_id     NUMBER,
    report_name   VARCHAR2(200)   NOT NULL,
    report_date   DATE            NOT NULL,
    report_file   VARCHAR2(500)   NOT NULL,

    CONSTRAINT pk_medical_reports PRIMARY KEY (report_id),

    CONSTRAINT fk_reports_patient
        FOREIGN KEY (patient_id)
        REFERENCES patients (patient_id)
        ON DELETE CASCADE,

    CONSTRAINT fk_reports_record
        FOREIGN KEY (record_id)
        REFERENCES medical_records (record_id)
        ON DELETE SET NULL
);


-- =====================================================================
--  5. PRESCRIPTIONS
--  record_id is optional because a doctor may create a prescription
--  directly after selecting a patient.
-- =====================================================================
CREATE TABLE prescriptions (
    prescription_id    NUMBER GENERATED BY DEFAULT AS IDENTITY,
    patient_id         NUMBER          NOT NULL,
    doctor_id          NUMBER          NOT NULL,
    record_id          NUMBER,
    prescription_date  DATE            DEFAULT SYSDATE NOT NULL,
    status             VARCHAR2(20)    DEFAULT 'Active' NOT NULL,
    doctor_notes       VARCHAR2(2000),

    CONSTRAINT pk_prescriptions PRIMARY KEY (prescription_id),

    CONSTRAINT fk_presc_patient
        FOREIGN KEY (patient_id)
        REFERENCES patients (patient_id)
        ON DELETE CASCADE,

    CONSTRAINT fk_presc_doctor
        FOREIGN KEY (doctor_id)
        REFERENCES doctors (doctor_id),

    CONSTRAINT fk_presc_record
        FOREIGN KEY (record_id)
        REFERENCES medical_records (record_id)
        ON DELETE SET NULL,

    CONSTRAINT ck_presc_status
        CHECK (status IN ('Active', 'Completed', 'Cancelled'))
);


-- =====================================================================
--  6. PRESCRIPTION_MEDICINES
--  morning / afternoon / night:
--  1 = medicine taken at that time, 0 = not taken at that time.
-- =====================================================================
CREATE TABLE prescription_medicines (
    medicine_id      NUMBER GENERATED BY DEFAULT AS IDENTITY,
    prescription_id  NUMBER          NOT NULL,
    medicine_name    VARCHAR2(200)   NOT NULL,
    dosage           VARCHAR2(100)   NOT NULL,
    morning          NUMBER(1)       DEFAULT 0,
    afternoon        NUMBER(1)       DEFAULT 0,
    night            NUMBER(1)       DEFAULT 0,
    duration         VARCHAR2(100)   NOT NULL,
    instruction      VARCHAR2(500)   NOT NULL,

    CONSTRAINT pk_prescription_medicines PRIMARY KEY (medicine_id),

    CONSTRAINT fk_meds_prescription
        FOREIGN KEY (prescription_id)
        REFERENCES prescriptions (prescription_id)
        ON DELETE CASCADE,

    CONSTRAINT ck_meds_morning
        CHECK (morning IN (0, 1)),

    CONSTRAINT ck_meds_afternoon
        CHECK (afternoon IN (0, 1)),

    CONSTRAINT ck_meds_night
        CHECK (night IN (0, 1))
);


-- =====================================================================
--  7. QR_CODES
--  One patient has one QR code because patient_id is UNIQUE.
-- =====================================================================
CREATE TABLE qr_codes (
    qr_id         NUMBER GENERATED BY DEFAULT AS IDENTITY,
    patient_id    NUMBER          NOT NULL,
    qr_data       VARCHAR2(255)   NOT NULL,
    generated_at  TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    status        VARCHAR2(20)    DEFAULT 'Active' NOT NULL,

    CONSTRAINT pk_qr_codes PRIMARY KEY (qr_id),

    CONSTRAINT uq_qr_patient
        UNIQUE (patient_id),

    CONSTRAINT uq_qr_data
        UNIQUE (qr_data),

    CONSTRAINT fk_qr_patient
        FOREIGN KEY (patient_id)
        REFERENCES patients (patient_id)
        ON DELETE CASCADE,

    CONSTRAINT ck_qr_status
        CHECK (status IN ('Active', 'Inactive'))
);


-- =====================================================================
--  8. INDEXES ON FOREIGN-KEY COLUMNS
--  Primary-key and unique constraints already create indexes.
--  These additional indexes support joins and foreign-key operations.
-- =====================================================================
CREATE INDEX idx_records_patient
    ON medical_records (patient_id);

CREATE INDEX idx_records_doctor
    ON medical_records (doctor_id);

CREATE INDEX idx_reports_patient
    ON medical_reports (patient_id);

CREATE INDEX idx_reports_record
    ON medical_reports (record_id);

CREATE INDEX idx_presc_patient
    ON prescriptions (patient_id);

CREATE INDEX idx_presc_doctor
    ON prescriptions (doctor_id);

CREATE INDEX idx_presc_record
    ON prescriptions (record_id);

CREATE INDEX idx_meds_prescription
    ON prescription_medicines (prescription_id);


-- =====================================================================
--  9. SAMPLE DATA (OPTIONAL — FOR TESTING / DEMO ONLY)
--  This data is inserted only once into a fresh database.
--  password_hash values are placeholders, not actual bcrypt hashes.
-- =====================================================================

-- Sample doctor
INSERT INTO doctors (
    doctor_name,
    license_number,
    specialization,
    qualification,
    email,
    mobile,
    password_hash,
    hospital_name
)
VALUES (
    'Dr. Amit Sharma',
    'MH-2015-48213',
    'General Physician',
    'MBBS, MD',
    'amit.sharma@example.com',
    '9876500001',
    'PLACEHOLDER_HASH',
    'City Hospital'
);


-- Sample patient
INSERT INTO patients (
    patient_code,
    patient_name,
    date_of_birth,
    gender,
    blood_group,
    phone,
    email,
    password_hash,
    height,
    weight,
    allergy,
    emergency_contact_name,
    emergency_contact_relation,
    emergency_contact_phone,
    address,
    city,
    state
)
VALUES (
    'MQ2026001',
    'Harshita Shah',
    DATE '2001-03-15',
    'Female',
    'B+',
    '9876543211',
    'harshita@example.com',
    'PLACEHOLDER_HASH',
    160,
    55,
    'None',
    'Rakesh Shah',
    'Father',
    '9876543210',
    'Sample Address',
    'Pune',
    'Maharashtra'
);


-- Sample QR code for the patient
INSERT INTO qr_codes (
    patient_id,
    qr_data
)
VALUES (
    (
        SELECT patient_id
        FROM patients
        WHERE patient_code = 'MQ2026001'
    ),
    'MQ2026001'
);


-- Sample medical record
INSERT INTO medical_records (
    patient_id,
    doctor_id,
    record_date,
    diagnosis,
    treatment
)
VALUES (
    (
        SELECT patient_id
        FROM patients
        WHERE patient_code = 'MQ2026001'
    ),
    (
        SELECT doctor_id
        FROM doctors
        WHERE license_number = 'MH-2015-48213'
    ),
    DATE '2026-07-20',
    'General Checkup',
    'Regular Medicines'
);


-- Sample medical report linked to the above medical record
INSERT INTO medical_reports (
    patient_id,
    record_id,
    report_name,
    report_date,
    report_file
)
VALUES (
    (
        SELECT patient_id
        FROM patients
        WHERE patient_code = 'MQ2026001'
    ),
    (
        SELECT record_id
        FROM medical_records
        WHERE patient_id = (
            SELECT patient_id
            FROM patients
            WHERE patient_code = 'MQ2026001'
        )
        AND doctor_id = (
            SELECT doctor_id
            FROM doctors
            WHERE license_number = 'MH-2015-48213'
        )
        AND record_date = DATE '2026-07-20'
    ),
    'Blood Test Report',
    DATE '2026-07-20',
    'uploads/blood-test-report.jpg'
);


-- Sample prescription linked to the same record
INSERT INTO prescriptions (
    patient_id,
    doctor_id,
    record_id,
    prescription_date,
    status,
    doctor_notes
)
VALUES (
    (
        SELECT patient_id
        FROM patients
        WHERE patient_code = 'MQ2026001'
    ),
    (
        SELECT doctor_id
        FROM doctors
        WHERE license_number = 'MH-2015-48213'
    ),
    (
        SELECT record_id
        FROM medical_records
        WHERE patient_id = (
            SELECT patient_id
            FROM patients
            WHERE patient_code = 'MQ2026001'
        )
        AND doctor_id = (
            SELECT doctor_id
            FROM doctors
            WHERE license_number = 'MH-2015-48213'
        )
        AND record_date = DATE '2026-07-20'
    ),
    DATE '2026-07-21',
    'Active',
    'Drink plenty of water. Avoid oily and spicy food. Visit again after 7 days.'
);


-- First medicine for the sample prescription
INSERT INTO prescription_medicines (
    prescription_id,
    medicine_name,
    dosage,
    morning,
    afternoon,
    night,
    duration,
    instruction
)
VALUES (
    (
        SELECT prescription_id
        FROM prescriptions
        WHERE patient_id = (
            SELECT patient_id
            FROM patients
            WHERE patient_code = 'MQ2026001'
        )
        AND prescription_date = DATE '2026-07-21'
    ),
    'Paracetamol',
    '500 mg',
    1,
    0,
    1,
    '5 Days',
    'After Food'
);


-- Second medicine for the same sample prescription
INSERT INTO prescription_medicines (
    prescription_id,
    medicine_name,
    dosage,
    morning,
    afternoon,
    night,
    duration,
    instruction
)
VALUES (
    (
        SELECT prescription_id
        FROM prescriptions
        WHERE patient_id = (
            SELECT patient_id
            FROM patients
            WHERE patient_code = 'MQ2026001'
        )
        AND prescription_date = DATE '2026-07-21'
    ),
    'Pantoprazole',
    '40 mg',
    1,
    0,
    0,
    '7 Days',
    'Before Food'
);


COMMIT;